### ISSUE TITLE
Make doWithModel async

### ISSUE THREAD

**Issue by GustavoFigueira** [Nhowka/FlutterMVU#1]
Hi,

I was wondering if it makes sense to make this Function asynchronous. In cases where doWithModel processing is also asynchronous and time-consuming, and we have to wait for this response to make another request.

![image](https://user-images.githubusercontent.com/15182680/186456438-cf2b7e48-21f8-4209-bc17-0adbb6ae9233.png)

Example:
![image](https://user-images.githubusercontent.com/15182680/186456863-ba4084e3-0aef-4136-a368-034ff3e58cce.png)

That makes sense? Or I didn't understand the MVU paradigm and can it be done another way?

Thanks.

**Comment by Nhowka** [comment]
Hi, @GustavoFigueira! `doWithModel` creates non-blocking code that could be used for simple notifications using the model's current state where you can fire and forget. While you could use `doWithModel` for things where you wait for the result, that would not be the best use case. For those, the recommended usage would be:

```dart
commandDispatcher(Cmd.ofModelAction((model) async {
    // do something with the model here
}, onSuccessModel: (model) {
   // do something when the previous action finishes
   return model;
});
```

Or, if you need to wait until certain things happen, `doWithModel` can be used with the help of `Completer`:

```dart
Future<void> blockingCall() {
   final c = Completer();
   doWithModel((model) async {
   // do something with the model
       c.complete(); // Complete the future to stop waiting for it
   // do more things    
   }
   return c.future; // Return the future that the completer creates
}
```

Let me know if the proposed solution works for your case!
